Fix issue with leaf/nodes in RecursiveXYCut that only have whitespaces words.
UglyToad/PdfPig pull request #100
Opened 2019-12-10 21:39 UTC by huzhiguan

In VerticalCut and HorizontalCut, it's using `CountWords() <= 1` as part of the condition to stop cutting with small text segments. This function doesn't exclude all the whitespace words. I made changes to make sure that those two functions will return when finding  XYLeaf/XYNode only have whitespaces words.

In `GetBlocks()`, if the returned node is an XYLeaf node, the `node.GetLeafs()` will return null which will cause the following lines to throw an exception.  I modified that part to make sure it's handling leaf node differently.

2019-12-11 15:21 UTC, BobLd requested changes
Some formatting comments

2019-12-11 15:21 UTC, BobLd commented on src/UglyToad.PdfPig/DocumentLayoutAnalysis/RecursiveXYCut.cs
> +            }
Go to line here

2019-12-11 15:21 UTC, BobLd commented on src/UglyToad.PdfPig/DocumentLayoutAnalysis/RecursiveXYCut.cs
Remove line here

2019-12-11 16:16 UTC, BobLd approved these changes
Thanks for your help on that!

2019-12-11 16:43 UTC, huzhiguan commented
> Thanks for your help on that!

You're welcome. Thank you all for the great project!

2019-12-14 16:44 UTC, merged

2019-12-14 16:44 UTC, EliotJones commented
Thank you for the contribution and sorry for the delay in merging.