Enable nullable annotations
UglyToad/PdfPig pull request #803
Opened 2024-03-16 22:33 UTC by iamcarbon

This PR enables nullable annotations on the main library.

2024-03-16 22:33 UTC, iamcarbon commented
@EliotJones @BobLd Ready for feedback / review.

2024-03-17 10:17 UTC, BobLd commented
@iamcarbon thanks a lot, I'll review it shortly

2024-03-17 14:57 UTC, BobLd commented
@iamcarbon I've added comments. Thanks a lot for the work! As a side note, when working on very large PRs (many files to review), let's try to keep the focus of the PR on a single item (e.g. nullable). If you notice issue or bugs during your changes, I'm more than happy for you to create a separate PR to address these issues. Thanks

2024-03-17 17:41 UTC, iamcarbon commented
@BobLd Let me know if you submitted your comments -- I don't see the on GitHub yet. I'll be careful on any future PR's to keep things tightly scoped to individual items.

2024-03-17 17:43 UTC, BobLd requested changes

2024-03-17 17:43 UTC, BobLd commented
@iamcarbon my bad, they should be visible now

2024-03-17 18:02 UTC, iamcarbon commented on src/UglyToad.PdfPig/Polyfills/NullableAnnotations.cs
A "Polyfill" conditionally patches an older framework to support newer framework features. It's been a more common pattern to back port modern .NET features to older features. It's possible we may want to add additional Polyfills for additional modern .NET features (e.g. to spanify streams), and these would be nicely contained here.

e.g. 

https://github.com/xoofx/markdig/tree/master/src/Markdig/Polyfills
https://www.meziantou.net/polyfills-in-dotnet-to-ease-multi-targeting.htm

2024-03-17 18:04 UTC, BobLd commented on src/UglyToad.PdfPig/Polyfills/NullableAnnotations.cs
sounds good, I didn't know this naming convention. Thx for the explaination

2024-03-17 18:08 UTC, iamcarbon commented on src/UglyToad.PdfPig/PdfDocument.cs
> +                if (IsEncrypted && encryptionDictionary != null)
encryptionDictionary is guaranteed to non-null when IsEncrypted is true. 

Adding this annotation made this extra check unnecessary. 

[MemberNotNullWhen(true, nameof(encryptionDictionary))]

2024-03-17 18:11 UTC, iamcarbon commented on src/UglyToad.PdfPig/Graphics/Colors/RGBWorkingSpace.cs
Without this change, these end up being errors with nullable annotations enabled.

We can, however, continue to always return false when passed a null color object to match the current behavior. 

Let me know if you have a preference.  

<img width="428" alt="Screenshot 2024-03-17 at 11 09 21 AM" src="https://github.com/UglyToad/PdfPig/assets/7537/54dcc4a5-d205-4454-882e-526f6cf0f2e4">

<img width="890" alt="Screenshot 2024-03-17 at 11 09 29 AM" src="https://github.com/UglyToad/PdfPig/assets/7537/134c96a4-69c5-4789-b162-1f644bcb1708">

2024-03-17 18:20 UTC, iamcarbon commented on src/UglyToad.PdfPig/Tokenization/Scanner/PdfTokenScanner.cs
> +                return null!;
Very few of this methods callers check for null, and this resulted in a significant number  "!" suppressions.

For now, I opted this method out of nullability so we can improve further in the future.

As a better solution, I'm wondering if we split this function into two variants:

```
ObjectToken? Find(IndirectReference) -> returns null if not found
ObjectToken Get(IndirectReference) -> throws if not found

```

2024-03-17 18:21 UTC, iamcarbon commented on src/UglyToad.PdfPig/Content/Page.cs
> +                return mcesOptional.GroupBy(oc => oc.Name).ToDictionary(g => g.Key!, g => (IReadOnlyList<OptionalContentGroupElement>)g.ToList());
Yep, this function continues to return a list. Moving the cast to the left just prevented this from being null.

2024-03-17 18:21 UTC, iamcarbon commented
@BobLd Thanks for the review! Comments above.

2024-03-17 18:22 UTC, BobLd commented on src/UglyToad.PdfPig/Tokenization/Scanner/PdfTokenScanner.cs
> +                return null!;
okay I see, that makes sense. Let's leave it like that for the moment, and possibly implement your idea in a later PR

2024-03-17 18:30 UTC, BobLd requested changes

2024-03-17 18:30 UTC, BobLd commented on src/UglyToad.PdfPig/Graphics/Colors/RGBWorkingSpace.cs
This comment is refering `RGBWorkingSpace.cs`, not to `RGBColor.cs` as GitHub would make you believe

2024-03-17 18:31 UTC, BobLd commented
Maybe it will be easier to post my last comment here: in the RGBWorkingSpace.cs files, I see you made some changes to the color / matrices. Do you mind reverting those and createing a different PR for that?

2024-03-17 18:33 UTC, BobLd commented
Also do you mind adding the change to fix the nighlty build to this PR? I've created one here https://github.com/UglyToad/PdfPig/pull/804/files but that will be easier if it goes with yours - thx again!

2024-03-17 18:35 UTC, iamcarbon commented on src/UglyToad.PdfPig/Graphics/Colors/RGBWorkingSpace.cs
Oops! 

The constructor was added to the internal RGBWorkingSpace to ensure GammaCorrection was initialized as non null.

We can revert this change and suppress the nullability annotations on this file, if you prefer.

2024-03-17 18:40 UTC, iamcarbon commented
> Also do you mind adding the change to fix the nighlty build to this PR? I've created one here https://github.com/UglyToad/PdfPig/pull/804/files but that will be easier if it goes with yours - thx again!

done!

2024-03-17 18:41 UTC, BobLd commented on src/UglyToad.PdfPig/Graphics/Colors/RGBWorkingSpace.cs
ok my bad - github was showing diffs where there were none:

![image](https://github.com/UglyToad/PdfPig/assets/38405645/629599f1-b54e-4b25-a8d9-43c30427e460)


All good thne

2024-03-17 18:41 UTC, BobLd commented
okay I'm good - will be merged shortly

2024-03-17 18:50 UTC, BobLd approved these changes

2024-03-17 18:51 UTC, merged