Reduce allocations, 1 of x
UglyToad/PdfPig pull request #818
Opened 2024-04-12 19:51 UTC by iamcarbon

2024-04-12 20:06 UTC, iamcarbon commented
@BobLd Ready for review / feedback.

2024-04-14 13:51 UTC, BobLd commented
@iamcarbon can you include my PR changes from https://github.com/UglyToad/PdfPig/pull/817/commits/f7d1aee5ed73362cacfb25cf5013ec64bf639957 in this PR.

I want to avoid having to fix conflicts later on

2024-04-14 14:07 UTC, BobLd requested changes

2024-04-14 23:18 UTC, BobLd commented on src/UglyToad.PdfPig.Core/ReadHelper.cs
> +        private const int MaximumNumberStringLength = 20; // max length of a formatted Int64 value
Unless I'm mistaken, it's only positive numbers.

2024-04-15 02:53 UTC, iamcarbon commented on src/UglyToad.PdfPig.Core/ReadHelper.cs
> +        private const int MaximumNumberStringLength = 20; // max length of a formatted Int64 value
Yep, these should always be unsigned. I split these max values based on whether we're reading an Int32 or Int64 value to the max unsigned length, and eliminated the additional byte[] allocation here.

2024-04-15 02:53 UTC, iamcarbon commented
> @iamcarbon can you include my PR changes from [f7d1aee](https://github.com/UglyToad/PdfPig/commit/f7d1aee5ed73362cacfb25cf5013ec64bf639957) in this PR.
> 
> I want to avoid having to fix conflicts later on

Included!

2024-04-18 18:58 UTC, BobLd approved these changes

2024-04-18 18:58 UTC, merged